### ISSUE TITLE
The weights file link provided is not consistent with the baseline code

### ISSUE THREAD

**Issue by jayjunjieqiu** [ASC-Competition/ASC24-LLM-inference-optimization#2]
Since the baseline code is written via `Transformers`, the link of weights file should be https://huggingface.co/meta-llama/Llama-2-70b-hf instead of https://huggingface.co/meta-llama/Llama-2-70b

**Comment by ASC-Competition** [comment]
Yes, if you want to use the baseline code, hf weights are requested and if you use other methods perhaps meta version weights are needed.  We will add the hf weight website to the readme, thank you.
