### ISSUE TITLE
Regarding Specific Guidance on Building an Inference System

### ISSUE THREAD

**Issue by Lvjinhong** [ASC-Competition/ASC24-LLM-inference-optimization#3]
## Application of Sampling Optimization Algorithm
In the competition, the decoding phase is also included in the timing interval. Under these circumstances, is it permissible to use sampling optimization algorithms to improve processing efficiency? Or is the focus of the competition solely on optimizing end-to-end inference latency?

## Regarding Specific Guidance on Building an Inference System
Regarding the "recommendation to build your own system" mentioned in the competition, I would like more clarity on its meaning. Does this imply that we should optimize based on existing frameworks or implement some new algorithms? Alternatively, does the committee expect us to start from scratch and independently build a new inference engine?

**Comment by ASC-Competition** [comment]
> ## Application of Sampling Optimization Algorithm
> In the competition, the decoding phase is also included in the timing interval. Under these circumstances, is it permissible to use sampling optimization algorithms to improve processing efficiency? Or is the focus of the competition solely on optimizing end-to-end inference latency?

Greedy search is used in the baseline code, and sampling is not the point. End-to-end throughput is a point concerned during the preliminary process but not all. The method and optimization used during the preliminary as well as the performance improvements brought by the optimization are also concerned, which should be clearly presented in the proposal.

> ## Regarding Specific Guidance on Building an Inference System
> Regarding the "recommendation to build your own system" mentioned in the competition, I would like more clarity on its meaning. Does this imply that we should optimize based on existing frameworks or implement some new algorithms? Alternatively, does the committee expect us to start from scratch and independently build a new inference engine?

The ASC24 committee don't set too many limits, you can build a totally new inference engine or modified the baseline code based on other methods, they are both "your own system". One thing worth be noted is that all the methods should be clearly presented in the proposal.

**Comment by Lvjinhong** [comment]
> > ## Application of Sampling Optimization Algorithm
> > In the competition, the decoding phase is also included in the timing interval. Under these circumstances, is it permissible to use sampling optimization algorithms to improve processing efficiency? Or is the focus of the competition solely on optimizing end-to-end inference latency?
> 
> Greedy search is used in the baseline code, and sampling is not the point. End-to-end throughput is a point concerned during the preliminary process but not all. The method and optimization used during the preliminary as well as the performance improvements brought by the optimization are also concerned, which should be clearly presented in the proposal.
> 
> > ## Regarding Specific Guidance on Building an Inference System
> > Regarding the "recommendation to build your own system" mentioned in the competition, I would like more clarity on its meaning. Does this imply that we should optimize based on existing frameworks or implement some new algorithms? Alternatively, does the committee expect us to start from scratch and independently build a new inference engine?
> 
> The ASC24 committee don't set too many limits, you can build a totally new inference engine or modified the baseline code based on other methods, they are both "your own system". One thing worth be noted is that all the methods should be clearly presented in the proposal.

Thank you very much for your response. Also, I have some questions regarding the baseline:

1.  When I modify the baseline code using different strategies during the generation process, I keep consistent parameters such as greedy search, temperature, top_p, etc. However, I noticed in my tests that the final sum of output tokens is less than the baseline's, because sometimes the generation in my code does not reach the max tokens. Is this acceptable, considering that the throughput is ultimately what matters?

2.  Regarding the baseline, I understand that the batch size should be 1, which means we can't change the strategy of this loop, right?  `for i in tqdm(range(len(requests)))`.

**Comment by ASC-Competition** [comment]
> 1. When I modify the baseline code using different strategies during the generation process, I keep consistent parameters such as greedy search, temperature, top_p, etc. However, I noticed in my tests that the final sum of output tokens is less than the baseline's, because sometimes the generation in my code does not reach the max tokens. Is this acceptable, considering that the throughput is ultimately what matters?

We have several tests and obtained the same numbers of output tokens. perphaps you can try to set the `min_new_toknes` parameters. 
>2. Regarding the baseline, I understand that the batch size should be 1, which means we can't change the strategy of this loop, right?  `for i in tqdm(range(len(requests)))`.

You can change the loop strategy. As mentioned above, the ASC24 committee don't set too many limits under the premise of fairness.

BTY, if you have any question you can contact the email [info@asc-events.org](mailto:info@asc-events.org). It will be replied as soon as possible.
