### ISSUE TITLE
Whether to allow methods that use multiple model copies

### ISSUE THREAD

**Issue by Traveller2001** [ASC-Competition/ASC24-LLM-inference-optimization#4]
Hello. Can you please ask the question of inference acceleration, is it possible to use multiple copies of the model to process different requests in the dataset as a way of accelerating the inference requests for the entire dataset. Also would like to ask what is the key metric that the final scoring looks at, requests/s? @ASC-Competition

**Comment by ASC-Competition** [comment]
You can use multiple copies to accelerate the inference of entire dataset, but it is not recommended. The request/s is just one of the scoring point. The method and optimization you used during the preliminary as well as the performance improvements brought by the optimization are the aspects commetees concerned.
